from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('auth', auth, name='Auth kek'),
    path('terminal', terminal_show, name='Terminal Info'),
    path('terminal/add', terminal_add, name='Add Terminal'),
    path('terminal/<id>', terminal_update, name='Update Terminal'),
    path('runway', runway_show, name='Runways Info'),
    path('runway/add', runway_add, name='Add Runway'),
    path('runway/<id>', runway_update, name='Update Runway'),
    path('planes', plane_show, name='Planes Info'),
    path('planes/add', plane_add, name='Add Plane'),
    path('planes/<model>', plane_update, name='Update Plane'),
    path('gate', gates_show, name='Gates Info'),
    path('gate/add', gates_add, name='Add Gates'),
    path('gate/<id>', gates_update, name='Update Gates'),
    path('flight', flight_show, name='Flight Info'),
    path('flight/passengers/<id>', list_of_passengers, name='List of Passengers on a Flight'),
    path('flight/add', flight_add, name='Add Flight'),
    path('flight/<id>', flight_update, name='Update Flight'),
    path('storage', storage_show, name='Storage Info'),
    path('storage/add', storage_add, name='Add Storage'),
    path('storage/<id>', storage_update, name='Update Storage'),
    path('towers', control_tower_show, name='Control Towers Info'),
    path('towers/add', control_tower_add, name='Add Control Tower'),
    path('towers/<id>', control_tower_update, name='Update Control Tower'),
    path('fields', flight_field_show, name='Flight Fields Info'),
    path('fields/add', flight_field_add, name='Add Flight Field'),
    path('fields/<id>', flight_field_update, name='Update Flight Field'),
    path('hangar', hangar_show, name='Hangar Info'),
    path('hangar/add', hangar_add, name='Add Hangar'),
    path('hangar/<id>', hangar_update, name='Update Hangar'),
    path('passengers', passenger_show, name='Passengers Info'),
    path('passengers/add', passenger_add, name='Add Passenger'),
    path('passengers/<id>', passenger_update, name='Update Passenger'),
    path('security', security_show, name='Security Units Info'),
    path('security/add', security_add, name='Add Security Unit'),
    path('security/<id>', security_update, name='Update Security Unit'),
]
