# Generated by Django 2.0 on 2018-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('shortname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'control_tower',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_arrival', models.DateTimeField(blank=True, null=True)),
                ('time_of_departure', models.DateTimeField(blank=True, null=True)),
                ('airline', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='FlightField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarmac_type', models.CharField(blank=True, max_length=255, null=True)),
                ('control_towerid', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'flight_field',
            },
        ),
        migrations.CreateModel(
            name='Gates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('throughput', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'gates',
            },
        ),
        migrations.CreateModel(
            name='Hangar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'hangar',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
                ('seat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('model', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('wingspan', models.IntegerField(blank=True, null=True)),
                ('num_of_seats', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'plane',
            },
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(blank=True, null=True)),
                ('tarmac_type', models.CharField(blank=True, max_length=255, null=True)),
                ('max_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'runway',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(blank=True, null=True)),
                ('k9_unit', models.NullBooleanField()),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'security',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('callsign', models.CharField(blank=True, max_length=255, null=True)),
                ('passenger_flow', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'terminal',
            },
        ),
    ]
